### ISSUE TITLE
Don't introduce root namespace "Platform"

### ISSUE THREAD

**Issue by c-s-n** [Azure/azure-amqp#141]
**Background**
Adding Microsoft.Azure.Amqp NuGet package to an existing project.

**Problem**
The package introduces a root namespace "Platform" (essentially only `Platform.System.Text`), which results in some name clashes for us.

**Expected behavior**
No such root namespace, especially since it feels unneeded.

Either place the `System.Text.Encoding` wrapping that is done in [PlatformSupport.cs](https://github.com/Azure/azure-amqp/blob/master/Microsoft.Azure.Amqp/PlatformSupport.cs) somewhere in the `Microsoft.Azure.Amqp` namespace, or directly use `System.Text.Encoding` with the corresponding directives.

**Comment by virtualcca** [comment]
when i reference this nuget
It made An enum or type called platform is incorrect

**Comment by Identifier** [comment]
This is still causing a problem as of the latest published NuGet package which is still v2.5.12 as of November 10 2022.  Specifically, it causes a conflict when importing the package into Unity since Unity's render pipeline has their own enum type named Platform and it conflicts with the Platform.System.Text namespace defined in v2.5.12 of Microsoft.Azure.Amqp.  See [this Unity issue](https://forum.unity.com/threads/shader-graph-and-possible-namespace-conflict.1181593/) for reference.

I see this was fixed 4 years ago on [November 8 2018](https://github.com/Azure/azure-amqp/commit/bbec5aa2e057505b32e06b3d1cd719772e995bf1) when the PlatformSupport.cs file was removed, but the change doesn't seem to have made it to NuGet yet.

@xinchen10 any idea when the current code will make its way to NuGet?

**Comment by JT-Bruch** [comment]
This is also blocking us as well, our whole codebase is prefixed "Platform" which is going to be a nightmare to unravel.

**Comment by taizoon** [comment]
Checking to see if there's a release date for this fix. Running into similar namespace conflicts. Thanks.
