### ISSUE TITLE
Can the TestAmqpBroker be used in integration tests that use Microsoft.Azure.EventHubs SDK?

### ISSUE THREAD

**Issue by briandunnington** [Azure/azure-amqp#155]
We have client code that uses the Microsoft.Azure.EventHubs SDK to send messages to an Event Hub. In order to run integration tests, we have to point it to a real Azure resource which is not desirable. I went looking for an emulator or in-memory AMQP implementation and stumbled upon this (well, actually upon amqpnetlite) and it seems like the TestAmqpBroker might be the ticket.
However, although I can launch the broker successfully, I am unsure how to connect to it from my calling code. Our real code uses an Azure Event Hub connection string with a SharedAccessKey (which I believe this does not support), so I tried using 'plain' authentication, but it appears that the Azure SDK does not support that (only SharedAccessKey and ManagedIdentity, if I am reading the source code correctly). When I try to send a message from my code, I get: `System.Net.Security: The handshake failed due to an unexpected packet format.` - Since it mentions 'handshake', I assume it is using some kind of Tls authentication or something?
I did see that the TestAmqpBroker supports custom transports - is there a way to launch the broker (or modify the code) to accept a SharedAccessKey over Tls (even if it does not validate them - it is only for running tests)? Has anybody done this successfully?

**Comment by xinchen10** [comment]
Even though the Event Hubs service and SDK speak AMQP, there are a few extensions and customizations on top. The SDK will not work against the test broker as is. The handshake error you got should be from SSL config mismatch. The SDK always use SSL+SASL. The test broker supports both if you enable them. This part is easy to fix.
The issue is missing components and custom addressing format. For example the test broker does not support CBS token authentication. For event hub the addresses from publisher and consumer need to be in certain format, especially for consumer. There are also some message properties expected by the SDK that the test broker does not set.
