### ISSUE TITLE
Strong name fixed in version 2.4.0.0

### ISSUE THREAD

**Issue by eddynaka** [Azure/azure-amqp#259]
Hello!

We recently observed that all new versions of the package Microsoft.Azure.Amqp has the binary strong named pinned with the version 2.4.0.0, which seems strange given that the package is being updated quite often:

https://nuget.info/packages/Microsoft.Azure.Amqp/2.6.7
![image](https://github.com/Azure/azure-amqp/assets/16199012/212b7963-73e8-4521-bf33-189d3b3c5e4a)

https://nuget.info/packages/Microsoft.Azure.Amqp/2.5.6
![image](https://github.com/Azure/azure-amqp/assets/16199012/373514d3-23e7-4ca3-951a-87783b63e4db)

Can the version be fixed, so that it won't cause confusion between package version vs binary version?

**Comment by xinchen10** [comment]
The assembly version was kept unchanged to avoid binding redirects when an application loads different versions of the library through direct and indirect references. The disadvantage is the confusion caused by the mismatch with the package versions. We will update the assembly version in next release.
