### ISSUE TITLE
Upgrading Microsoft.Azure.Amqp to version 2.1.0, 2.1.1 or 2.1.2 causes Azure IoT DeviceClient SDK to fail

### ISSUE THREAD

**Issue by CIPop** [Azure/azure-amqp#81]
@FelixXWS, @sodablue reported this potential regression in the AMQP library starting with version 2.1.0: 
https://github.com/Azure/azure-iot-sdk-csharp/issues/167

The Azure IoT Device SDK is currently using "Microsoft.Azure.Amqp" Version="2.0.6".

**Comment by xinchen10** [comment]
You are using the AMQP library indirectly through the IOT client which is built against the 2.0.6 package. That package contains the following strong named assembly.
Microsoft.Azure.Amqp, Version=2.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35

The AMQP package 2.1.0 contains the following strong named assembly.
Microsoft.Azure.Amqp, Version=2.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35

Notice that the minor version has been increased. When you manually update the AMQP library, NuGet automatically add the binding redirect in order to load the new version.
```
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Azure.Amqp" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-2.1.0.0" newVersion="2.1.0.0" />
      </dependentAssembly>
```

With binding redirect, there is no guarantee that everything will work as is. While we try the best to maintain backward compatibility, breaking changes sometimes happen. In the AMQP library, the public surface is unfortunately larger than ideal. Many of them are for internal implementation only. When we introduce breaking changes to those APIs, we increase the minor version. However we are aware that currently the APIs are very poorly documented. We are adding the documentation and will specifically call out the APIs that are not meant for public use.

**Comment by CIPop** [comment]
> Notice that the minor version has been increased. 

We did notice that and assumed SemVer in which minor increases are guaranteed to not have breaking changes. If that's not the case, then I assume we need to fix this on our side?
Do you have information on what may have changed for us to see this hang with the new version?

**Comment by candersonio** [comment]
> Do you have information on what may have changed for us to see this hang with the new version?

In case you haven't found it yet. I believe the breaking changeset is here:
https://github.com/Azure/azure-amqp/commit/9fb3dee97efc64c94b7ca511505085d963e4d884#diff-aafcd5eed57dc6edc69fb1916381bee1

TransportBase had two of its abstract members' return types changed from Endpoint to string. In Microsoft.Azure.Device.Client the ClientWebSocketTransport (and LegacyClientWebSocketTransport) class inherits TransportBase. I fixed and built this locally then included them into a demo test app and now AMQP over WebSocket works as expected.

**Comment by DeluxZ** [comment]
I don't know if my problem is really related to this one. But I'm getting a `Could not load file or assembly 'Microsoft.Azure.Amqp, Version=2.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.` when using Microsoft.Azure.Amqp **2.1.2** in an Azure Function. I'm just callig `var ioTRegistryClient = RegistryManager.CreateFromConnectionString(iotHubConnectionString);`. Binding redirects are the same as stated above. This disappears when I'm downgrading to **2.0.6**.

**Comment by xinchen10** [comment]
iot client has been updated to the latest version.
